name: Metrics

on:
  schedule: 
    - cron: "0 0 * * *"   # Updates daily
  workflow_dispatch:       # Allows manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohamedaatid 
          template: classic
          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
        

